### ISSUE TITLE
fatal error: EventLoop.h: No such file or directory

### ISSUE THREAD

**Issue by luckypoem** [airtrack/snet#1]
hi.

git clone https://github.com/airtrack/snet
cd snet/test/stunnel/
mkdir build
cd build
cmake ..

root@yms:~/snet/test/stunnel/build# cmake ..
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.10)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /root/snet/test/stunnel/build
root@yms:~/snet/test/stunnel/build# ls
CMakeCache.txt	CMakeFiles  cmake_install.cmake  Makefile
root@yms:~/snet/test/stunnel/build# make
Scanning dependencies of target sserver
[ 10%] Building CXX object CMakeFiles/sserver.dir/Relay.o
In file included from /root/snet/test/stunnel/Relay.cpp:1:0:
/root/snet/test/stunnel/Relay.h:4:23: fatal error: EventLoop.h: No such file or directory
 #include "EventLoop.h"
                       ^
compilation terminated.
CMakeFiles/sserver.dir/build.make:62: recipe for target 'CMakeFiles/sserver.dir/Relay.o' failed
make[2]: *** [CMakeFiles/sserver.dir/Relay.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/sserver.dir/all' failed
make[1]: *** [CMakeFiles/sserver.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
root@yms:~/snet/test/stunnel/build#

如何解决？谢谢

**Comment by airtrack** [comment]
请参考README.md
